[pytest]
testpaths =
    tests
    src/ms8/engine_core/tests
addopts =
    --cov=src/ms8
    --cov-branch
    --cov-config=.coveragerc
    --cov-report=term
    --cov-fail-under=42
filterwarnings =
    ignore::pytest.PytestWarning:_pytest.pathlib
