"""Governed Hybrid Retrieval v1 package boundary.

The package is experimental and not wired into the default runtime path.
"""

from .adapters import (
    CandidateBatch,
    CandidateRecord,
    CandidateSourceTrace,
    LedgerLexicalCandidateSource,
    LegacyCandidateMapper,
    LegacyCandidateProvider,
    LegacyGraphCandidateSource,
    LegacySemanticCandidateSource,
    LegacyWhooshCandidateSource,
    MappedLegacyCandidateSource,
    ProjectionCandidateProvider,
    ProjectionCandidateSource,
    SourceStatus,
    run_candidate_sources,
)
from .analyzer import QueryAnalysis, analyze_query
from .candidate_sources import (
    CandidateSource,
    CandidateSourceError,
    run_candidate_source,
    validate_candidate_hits,
)
from .eligibility import (
    EligibilityEvaluation,
    EligibilityEvaluator,
    EligibleClaims,
    PolicyDecision,
    PolicyHook,
    normalize_authority,
)
from .models import (
    CandidateChannel,
    CandidateHit,
    CandidateLimits,
    MemoryQuery,
    Principal,
    PrincipalKind,
    QueryIntent,
    RankedClaim,
    RetrievalPlan,
    RetrievalPurpose,
    RetrievalTrace,
    TimeCoordinates,
)
from .projection_sources import (
    EvidenceResolver,
    SearchProjectionCandidateProvider,
    SearchProjectionFormatError,
)
from .query_planner import (
    ClassifierHook,
    QueryPlanner,
    QueryPlanningResult,
    TemporalResolution,
    resolve_temporal_expression,
)

__all__ = [
    "CandidateBatch",
    "CandidateChannel",
    "CandidateHit",
    "CandidateLimits",
    "CandidateRecord",
    "CandidateSource",
    "CandidateSourceError",
    "CandidateSourceTrace",
    "ClassifierHook",
    "EligibilityEvaluation",
    "EligibilityEvaluator",
    "EligibleClaims",
    "EvidenceResolver",
    "LedgerLexicalCandidateSource",
    "LegacyCandidateMapper",
    "LegacyCandidateProvider",
    "LegacyGraphCandidateSource",
    "LegacySemanticCandidateSource",
    "LegacyWhooshCandidateSource",
    "MappedLegacyCandidateSource",
    "MemoryQuery",
    "PolicyDecision",
    "PolicyHook",
    "Principal",
    "PrincipalKind",
    "ProjectionCandidateProvider",
    "ProjectionCandidateSource",
    "QueryAnalysis",
    "QueryIntent",
    "QueryPlanner",
    "QueryPlanningResult",
    "RankedClaim",
    "RetrievalPlan",
    "RetrievalPurpose",
    "RetrievalTrace",
    "SearchProjectionCandidateProvider",
    "SearchProjectionFormatError",
    "SourceStatus",
    "TemporalResolution",
    "TimeCoordinates",
    "analyze_query",
    "normalize_authority",
    "resolve_temporal_expression",
    "run_candidate_source",
    "run_candidate_sources",
    "validate_candidate_hits",
]
