"""Governed Hybrid Retrieval v1 package boundary.

The package is experimental and not wired into the default runtime path.
"""

from .adapters import (
    CandidateBatch,
    CandidateRecord,
    CandidateSourceTrace,
    LedgerLexicalCandidateSource,
    LegacyCandidateMapper,
    LegacyCandidateProvider,
    LegacyGraphCandidateSource,
    LegacySemanticCandidateSource,
    LegacyWhooshCandidateSource,
    MappedLegacyCandidateSource,
    ProjectionCandidateProvider,
    ProjectionCandidateSource,
    SourceStatus,
    run_candidate_sources,
)
from .analyzer import QueryAnalysis, analyze_query
from .candidate_sources import (
    CandidateSource,
    CandidateSourceError,
    run_candidate_source,
    validate_candidate_hits,
)
from .context_assembly import (
    ContextAssemblyError,
    ContextAssemblyResult,
    MMRConfig,
    MMRSelectionResult,
    MMRSelectionTrace,
    SimilarityMode,
    assemble_context,
    build_agent_context,
    estimate_context_tokens,
    select_mmr,
)
from .eligibility import (
    EligibilityEvaluation,
    EligibilityEvaluator,
    EligibleClaims,
    PolicyDecision,
    PolicyHook,
    normalize_authority,
)
from .embedding import (
    ApproximateEmbeddingBackend,
    EmbeddingMatch,
    EmbeddingProvider,
    EmbeddingSearchError,
    exact_cosine_search,
    normalize_embedding_vector,
    validate_embedding_batch,
)
from .embedding_sources import (
    EmbeddingProjectionCandidateProvider,
    EmbeddingProjectionCandidateSource,
    EmbeddingProjectionFormatError,
)
from .entity_sources import (
    EntityProjectionCandidateProvider,
    EntityProjectionCandidateSource,
    EntityProjectionFormatError,
    normalize_entity_label,
)
from .fusion import (
    FUSION_CONFIG_SCHEMA,
    FusionConfig,
    FusionResult,
    fuse_and_rerank,
)
from .graph_sources import (
    GraphProjectionCandidateProvider,
    GraphProjectionCandidateSource,
    GraphProjectionFormatError,
)
from .models import (
    CandidateChannel,
    CandidateHit,
    CandidateLimits,
    MemoryQuery,
    Principal,
    PrincipalKind,
    QueryIntent,
    RankedClaim,
    RetrievalPlan,
    RetrievalPurpose,
    RetrievalTrace,
    TimeCoordinates,
)
from .ollama_embedding import OllamaEmbeddingError, OllamaEmbeddingProvider
from .projection_sources import (
    EvidenceResolver,
    SearchProjectionCandidateProvider,
    SearchProjectionFormatError,
)
from .query_planner import (
    ClassifierHook,
    QueryPlanner,
    QueryPlanningResult,
    TemporalResolution,
    resolve_temporal_expression,
)
from .temporal_sources import (
    TemporalReplayCandidateProvider,
    TemporalReplayCandidateSource,
)

__all__ = [
    "ApproximateEmbeddingBackend",
    "CandidateBatch",
    "CandidateChannel",
    "CandidateHit",
    "CandidateLimits",
    "CandidateRecord",
    "CandidateSource",
    "CandidateSourceError",
    "CandidateSourceTrace",
    "ClassifierHook",
    "ContextAssemblyError",
    "ContextAssemblyResult",
    "EligibilityEvaluation",
    "EligibilityEvaluator",
    "EligibleClaims",
    "EmbeddingMatch",
    "EmbeddingProjectionCandidateProvider",
    "EmbeddingProjectionCandidateSource",
    "EmbeddingProjectionFormatError",
    "EmbeddingProvider",
    "EmbeddingSearchError",
    "EntityProjectionCandidateProvider",
    "EntityProjectionCandidateSource",
    "EntityProjectionFormatError",
    "EvidenceResolver",
    "FUSION_CONFIG_SCHEMA",
    "FusionConfig",
    "FusionResult",
    "GraphProjectionCandidateProvider",
    "GraphProjectionCandidateSource",
    "GraphProjectionFormatError",
    "LedgerLexicalCandidateSource",
    "LegacyCandidateMapper",
    "LegacyCandidateProvider",
    "LegacyGraphCandidateSource",
    "LegacySemanticCandidateSource",
    "LegacyWhooshCandidateSource",
    "MMRConfig",
    "MMRSelectionResult",
    "MMRSelectionTrace",
    "MappedLegacyCandidateSource",
    "MemoryQuery",
    "OllamaEmbeddingError",
    "OllamaEmbeddingProvider",
    "PolicyDecision",
    "PolicyHook",
    "Principal",
    "PrincipalKind",
    "ProjectionCandidateProvider",
    "ProjectionCandidateSource",
    "QueryAnalysis",
    "QueryIntent",
    "QueryPlanner",
    "QueryPlanningResult",
    "RankedClaim",
    "RetrievalPlan",
    "RetrievalPurpose",
    "RetrievalTrace",
    "SearchProjectionCandidateProvider",
    "SearchProjectionFormatError",
    "SimilarityMode",
    "SourceStatus",
    "TemporalReplayCandidateProvider",
    "TemporalReplayCandidateSource",
    "TemporalResolution",
    "TimeCoordinates",
    "analyze_query",
    "assemble_context",
    "build_agent_context",
    "estimate_context_tokens",
    "exact_cosine_search",
    "fuse_and_rerank",
    "normalize_authority",
    "normalize_embedding_vector",
    "normalize_entity_label",
    "resolve_temporal_expression",
    "run_candidate_source",
    "run_candidate_sources",
    "select_mmr",
    "validate_candidate_hits",
    "validate_embedding_batch",
]
